import type React from 'react';

export const sectionStyles: Record<string, React.CSSProperties> = {
  sectionTitle: { margin: '0 0 8px 0', fontSize: '19px', fontWeight: 700, color: 'var(--color-text)' },
  description: { margin: '0 0 22px 0', fontSize: '14px', lineHeight: 1.6, color: 'var(--color-muted)' },
  empty: {
    padding: '20px',
    marginBottom: '16px',
    border: '1px dashed #c7ccd5',
    borderRadius: '12px',
    backgroundColor: '#f8f9fb',
    color: 'var(--color-muted)',
    fontSize: '14px',
    textAlign: 'center',
  },
  card: {
    padding: '16px',
    marginBottom: '16px',
    border: '1px solid var(--color-border)',
    borderRadius: '12px',
    backgroundColor: '#f8f9fb',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '14px',
  },
  cardIndex: { fontSize: '13px', fontWeight: 700, color: 'var(--color-primary)' },
  cardActions: { display: 'flex', gap: '6px' },
  iconButton: {
    minWidth: '44px',
    height: '26px',
    padding: '0 8px',
    border: '1px solid #d4d8df',
    borderRadius: '7px',
    backgroundColor: 'white',
    cursor: 'pointer',
    fontSize: '12px',
    color: 'var(--color-muted)',
  },
  removeButton: {
    padding: '0 10px',
    height: '26px',
    border: '1px solid #fecaca',
    borderRadius: '7px',
    backgroundColor: 'white',
    color: 'var(--color-danger)',
    cursor: 'pointer',
    fontSize: '12px',
    fontFamily: 'inherit',
  },
  row: { display: 'flex', gap: '12px', marginBottom: '12px' },
  group: { flex: 1, marginBottom: '12px' },
  label: {
    display: 'block',
    marginBottom: '6px',
    fontSize: '13px',
    fontWeight: 500,
    color: 'var(--color-text)',
  },
  input: {
    width: '100%',
    padding: '8px 10px',
    fontSize: '14px',
    border: '1px solid var(--color-border)',
    borderRadius: '9px',
    outline: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  textarea: {
    width: '100%',
    minHeight: '70px',
    padding: '8px 10px',
    fontSize: '14px',
    border: '1px solid var(--color-border)',
    borderRadius: '9px',
    outline: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    resize: 'vertical',
    lineHeight: 1.6,
  },
  addButton: {
    padding: '10px 18px',
    border: '1px solid #c7ccd5',
    borderRadius: '9px',
    backgroundColor: 'white',
    color: 'var(--color-primary)',
    fontSize: '14px',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
};
